#!/bin/bash

NAME=$1
if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ ! -d /tmp/$NAME ]; then echo "No such directory /tmp/$NAME."; exit 1; fi

echo "Pause."

kill `cat /tmp/$NAME/pid` 2> /dev/null
sleep 1
kill -9 `cat /tmp/$NAME/pid` 2> /dev/null
rm /tmp/$NAME/pid 2> /dev/null
