#!/bin/bash

PYTHONPATH2=
PYTHONPATH=/home/mininet/mininet_folder/
POX_CORE_DIR=/home/mininet/pox_folder/
CONFIG_FOLDER_LOCATION=.



cd $CONFIG_FOLDER_LOCATION
mkdir config 2> /dev/null
cd config

sudo env PYTHONPATH=$PYTHONPATH POX_CORE_DIR=$POX_CORE_DIR $PYTHONPATH/cmstest.py $@
