#!/bin/bash

if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi

mkdir server 2> /dev/null
cd server
echo "This is a basic file by $NAME." > file.txt
python -m SimpleHTTPServer &

cd ..
echo $! > pid
