#!/bin/bash

NAME=$1
if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ ! -d /tmp/$NAME ]; then echo "No such directory /tmp/$NAME."; exit 1; fi
cd /tmp/$NAME

cd client
rm file.txt 2> /dev/null
cd ..
rmdir client 2> /dev/null
