#!/bin/bash

NAME=$1
IP=$2
SERVER_IP=$3
if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ -z "$SERVER_IP" ]; then echo "SERVER_IP not set."; exit 1; fi

cd /tmp/$NAME

echo "Pause."

kill `cat /tmp/$NAME/pid` 2> /dev/null
sleep 1
kill -9 `cat /tmp/$NAME/pid` 2> /dev/null
rm /tmp/$NAME/pid 2> /dev/null
