#!/bin/bash

if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ -z "$SERVER_IP" ]; then echo "SERVER_IP not set."; exit 1; fi

echo "Pause."

kill `cat pid` 2> /dev/null
sleep 1
kill -9 `cat pid` 2> /dev/null
rm pid 2> /dev/null
