#!/bin/bash

NAME=$1
IP=$2
SERVER_IP=$3
if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ -z "$SERVER_IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ ! -d /tmp/$NAME ]; then echo "No such directory /tmp/$NAME."; exit 1; fi
cd /tmp/$NAME

cd folder_name
echo "Resume."

echo $! > /tmp/$NAME/pid
