#!/bin/bash

if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ -z "$SERVER_IP" ]; then echo "SERVER_IP not set."; exit 1; fi

mkdir folder_name 2> /dev/null
cd folder_name
echo "Start." &

cd ..
echo $! > pid
