#!/bin/bash

if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "SERVER_IP not set."; exit 1; fi
if [ -z "$SERVER_IP" ]; then echo "SERVER_IP not set."; exit 1; fi

cd folder_name
rm file_name 2> /dev/null
cd ..
rmdir folder_name 2> /dev/null

kill `cat pid` 2> /dev/null
sleep 1
kill -9 `cat pid` 2> /dev/null
rm pid 2> /dev/null
