#!/bin/bash

if [ -z "$NAME" ]; then echo "NAME not set."; exit 1; fi
if [ -z "$IP" ]; then echo "IP not set."; exit 1; fi
if [ -z "$REDIS_SERVER_IP" ]; then echo "REDIS_SERVER_IP not set."; exit 1; fi
if [ -z "$REDIS_SERVER_PORT" ]; then echo "REDIS_SERVER_PORT not set."; exit 1; fi
